### ISSUE TITLE
Add BDD feature and tests for Create draft data agreement

### ISSUE THREAD

**Issue by albinpa** [decentralised-dataexchange/bb-consent-docs#17]
An example BDD feature file can be found here - https://github.com/GovStackWorkingGroup/bb-consent/blob/main/test/gherkin/features/config_policy_create.feature

Use the following BDD python package for implementing the test harness - https://behave.readthedocs.io/en/latest/tutorial/#features

**Comment by georgepadayatti** [comment]
@lalc @kashishmalik Any inputs are welcomed. We can already start writing the features that needs to be tested and you guys can review it.
